event_night:
    resource: "@EventNightBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#REST
rest :
  type : rest
  resource: "@EventNightBundle/Resources/config/routing_rest.yml"
  prefix : /api/

